// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendCount(arg1:string):Promise<void>;

export function SendIndex(arg1:string):Promise<void>;

export function SendSearch(arg1:string,arg2:string,arg3:boolean):Promise<void>;
