// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendCount(arg1) {
  return window['go']['main']['App']['SendCount'](arg1);
}

export function SendIndex(arg1) {
  return window['go']['main']['App']['SendIndex'](arg1);
}

export function SendSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendSearch'](arg1, arg2, arg3);
}
